# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a4d114a4e0aa6a70af1d9205f8ff678ab437a3bfc8a04b468f929be0f9f8694d107a3651a44e4b772b881049684973f4695b25da7093e3f97b15f22bdf258e8

test:
  secret_key_base: ccb3d2321b43ce15905160833b1911063fcbfc7a43a6db67a0e47bce11e8536872a47c5abf8f164aa0a3e119f3ba8c07ab8b3cd338fe2a73fe1acac367fe4250

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
